//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace operacionMascota.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONACIONES
    {
        public long ID_DONAR { get; set; }
        public Nullable<long> ID_TIPOD { get; set; }
        public long ID_PERSONA { get; set; }
        public byte[] FOTO_BOLETA { get; set; }
        public byte[] FOTO_BOLETA2 { get; set; }
        public byte[] FOTO_BOLETA3 { get; set; }
        public string USER_CREAR_DN { get; set; }
        public string USER_ELIMINAR_DN { get; set; }
        public string USER_ACTUALIZAR_DN { get; set; }
        public Nullable<System.DateTime> USER_CREAR_FDN { get; set; }
        public Nullable<System.DateTime> USER_ELIMINAR_FDN { get; set; }
        public Nullable<System.DateTime> USER_ACTUALIZAR_FDN { get; set; }
    
        public virtual TIPO_DONACION TIPO_DONACION { get; set; }
    }
}
