//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace operacionMascota.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASCOTA
    {
        public long ID_MASCOTA { get; set; }
        public long ID_COMUNA { get; set; }
        public Nullable<long> ID_TIPOM { get; set; }
        public Nullable<long> ID_GENERO { get; set; }
        public string NICK_MASCOTA { get; set; }
        public string TAMANO { get; set; }
        public byte[] FOTO_M1 { get; set; }
        public byte[] FOTO_M2 { get; set; }
        public byte[] FOTO_M3 { get; set; }
        public string USER_CREAR_MASCOTA { get; set; }
        public string USER_ELIMINAR_MASCOTA { get; set; }
        public string USER_ACTUALIZAR_MASCOTA { get; set; }
        public Nullable<System.DateTime> USER_CREAR_FMASC { get; set; }
        public Nullable<System.DateTime> USER_ELIMINAR_FMASC { get; set; }
        public Nullable<System.DateTime> USER_ACTUALIZAR_FMASC { get; set; }
    
        public virtual ADOPTAR_MASCOTA ADOPTAR_MASCOTA { get; set; }
        public virtual COMUNAS COMUNAS { get; set; }
        public virtual GENERO_MASCOTA GENERO_MASCOTA { get; set; }
        public virtual TIPO_MASCOTA TIPO_MASCOTA { get; set; }
        public virtual REGISTRO_ADOPCION REGISTRO_ADOPCION { get; set; }
    }
}
