//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace operacionMascota.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class opemascotasEntities : DbContext
    {
        public opemascotasEntities()
            : base("name=opemascotasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADOPTAR_MASCOTA> ADOPTAR_MASCOTA { get; set; }
        public virtual DbSet<CIUDADES> CIUDADES { get; set; }
        public virtual DbSet<COMUNAS> COMUNAS { get; set; }
        public virtual DbSet<DONACIONES> DONACIONES { get; set; }
        public virtual DbSet<GENERO_MASCOTA> GENERO_MASCOTA { get; set; }
        public virtual DbSet<LISTA_NEGRA> LISTA_NEGRA { get; set; }
        public virtual DbSet<MASCOTA> MASCOTA { get; set; }
        public virtual DbSet<MASCOTA_ABANDONADA> MASCOTA_ABANDONADA { get; set; }
        public virtual DbSet<PAISES> PAISES { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<REGIONES> REGIONES { get; set; }
        public virtual DbSet<REGISTRO_ADOPCION> REGISTRO_ADOPCION { get; set; }
        public virtual DbSet<REGISTRO_DONACION> REGISTRO_DONACION { get; set; }
        public virtual DbSet<SEGUIMIENTO_ADOPCION> SEGUIMIENTO_ADOPCION { get; set; }
        public virtual DbSet<SOLICITUD_DONACIONES> SOLICITUD_DONACIONES { get; set; }
        public virtual DbSet<TIPO_DONACION> TIPO_DONACION { get; set; }
        public virtual DbSet<TIPO_MASCOTA> TIPO_MASCOTA { get; set; }
        public virtual DbSet<TIPO_PERSONA> TIPO_PERSONA { get; set; }
        public virtual DbSet<UBICACION_MASCOTA> UBICACION_MASCOTA { get; set; }
        public virtual DbSet<USUARIO_LISTA> USUARIO_LISTA { get; set; }
    }
}
