//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace operacionMascota.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_DONACIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLICITUD_DONACIONES()
        {
            this.REGISTRO_DONACION = new HashSet<REGISTRO_DONACION>();
        }
    
        public long ID_SOLICITUD { get; set; }
        public Nullable<long> SOLICITUD1 { get; set; }
        public Nullable<long> SOLICITUD2 { get; set; }
        public byte[] FOTO_BOLETA1 { get; set; }
        public byte[] FOTO_BOLETA2 { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public string USER_CREAR_SD { get; set; }
        public string USER_ELIMINAR_SD { get; set; }
        public string USER_ACTUALIZAR_SD { get; set; }
        public Nullable<System.DateTime> USER_CREAR_FSD { get; set; }
        public Nullable<System.DateTime> USER_ELIMINAR_FSD { get; set; }
        public Nullable<System.DateTime> USER_ACTUALIZAR_FSD { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_DONACION> REGISTRO_DONACION { get; set; }
    }
}
