//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace operacionMascota.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_PERSONA()
        {
            this.PERSONA = new HashSet<PERSONA>();
        }
    
        public long ID_TPERSONA { get; set; }
        public string TIPO_PERSONA1 { get; set; }
        public string USER_CREAR_TP { get; set; }
        public string USER_ELIMINAR_TP { get; set; }
        public string USER_ACTUALIZAR_TP { get; set; }
        public Nullable<System.DateTime> USER_CREAR_FTP { get; set; }
        public Nullable<System.DateTime> USER_ELIMINAR_FTP { get; set; }
        public Nullable<System.DateTime> USER_ACTUALIZAR_FTP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONA> PERSONA { get; set; }
    }
}
