//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace operacionMascota.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADOPTAR_MASCOTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADOPTAR_MASCOTA()
        {
            this.SEGUIMIENTO_ADOPCION = new HashSet<SEGUIMIENTO_ADOPCION>();
        }
    
        public long ID_AD { get; set; }
        public Nullable<long> ID_MASCOTA { get; set; }
        public Nullable<bool> ADOPTADO { get; set; }
        public string USER_CREAR_AD { get; set; }
        public string USER_ELIMINAR_AD { get; set; }
        public string USER_ACTUALIZAR_AD { get; set; }
        public Nullable<System.DateTime> USER_CREAR_FAD { get; set; }
        public Nullable<System.DateTime> USER_ELIMINAR_FAD { get; set; }
        public Nullable<System.DateTime> USER_ACTUALIZAR_FAD { get; set; }
    
        public virtual MASCOTA MASCOTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEGUIMIENTO_ADOPCION> SEGUIMIENTO_ADOPCION { get; set; }
    }
}
