//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace operacionMascota.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_ADOPCION
    {
        public long ID_REGISTRO { get; set; }
        public Nullable<long> ID_MASCOTA { get; set; }
        public Nullable<long> ID_PERSONA { get; set; }
    
        public virtual MASCOTA MASCOTA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
